module RedmineAgent
  # Setting.plugin_redmine_agent= is regenerated by Setting.define_setting as a
  # plain replace: SettingsController#plugin posts only the fields on the
  # settings form, so saving it would silently wipe custom_agents/runs, which
  # never appear on that form. This keeps those keys across a save.
  module SettingPatch
    PRESERVED_KEYS = %w[custom_agents custom_agents_seeded].freeze

    def self.apply!
      return if Setting.singleton_class.method_defined?(:_redmine_agent_org_plugin_setting=)

      Setting.singleton_class.send(:alias_method, :_redmine_agent_org_plugin_setting=, :plugin_redmine_agent=)
      Setting.define_singleton_method(:plugin_redmine_agent=) do |value|
        if value.is_a?(Hash)
          preserved = (plugin_redmine_agent || {}).slice(*RedmineAgent::SettingPatch::PRESERVED_KEYS)
          value = preserved.merge(value.stringify_keys)
        end
        self._redmine_agent_org_plugin_setting = value
      end
    end
  end
end
